Feat/new registration logic 2
virtualidentityag/diakonie-onlineBeratung-frontend pull request #15
Opened 2023-06-15 06:10 UTC by RunzelRosinchen

2023-06-28 07:10 UTC, web-mi commented on src/resources/scripts/endpoints.ts
> +	isUsernameAvailable: apiUrl + '/service/users',
Das ist eigentlich nur der base Pfad zum UserService. Ich würde es dann eher baseUserService oder sowas nennen.

2023-06-28 07:10 UTC, web-mi commented on src/resources/i18n/de.json
> +			"infoOverlay": {
Fehlt der Teil in en.json?

2023-06-28 07:10 UTC, web-mi commented on src/resources/i18n/de.json
> +			"infoOverlay": {
Fehlt der Teil in en.json?

2023-06-28 07:10 UTC, web-mi commented on src/resources/i18n/de.json
> +					"available": "Ihr Benutzername ist zu kurz.",
Sollen wir hier auch einfach "Dieser Benutzername ist zu kurz" draus machen? Dann ists einheitlich

2023-06-28 07:10 UTC, web-mi commented on package-lock.json
Ist die wieder messed up? Sieht mir nach zu vielen changed lines aus

2023-06-28 07:10 UTC, web-mi commented on src/api/apiGetTopicGroups.ts
> +	data: { items: Array<any> };
Type defintion

2023-06-28 07:10 UTC, web-mi commented on src/components/app/app.tsx
> +										<RegistrationProvider>
Reicht der RegistrationProvider nicht wenn er um den RegistrationWrapper ist?

2023-06-28 07:10 UTC, web-mi commented on src/components/input/input.tsx
> +				onChange={async (e) => {
Das würde ich oben in eine handleChange Methode packen

2023-06-28 07:10 UTC, web-mi commented on src/components/input/input.tsx
> +				onBlur={async () => {
handleBlur

2023-07-03 05:42 UTC, RunzelRosinchen commented on src/components/app/app.tsx
> +										<RegistrationProvider>
Ja, das hab ich in der nächsten PR geändert, würde ich hier also lassen wenns passt

2023-07-03 05:49 UTC, RunzelRosinchen commented on src/resources/i18n/de.json
> +					"available": "Ihr Benutzername ist zu kurz.",
Wir haben nur einmal "Dieser" sonst immer Ihr (Ihr Passwort ist  identisch. Ihr Benutzername ist geeignet...)

2023-07-06 08:13 UTC, SheepFromHeaven requested changes

2023-07-06 08:13 UTC, SheepFromHeaven commented on src/components/input/input.tsx
> +	isValueValid?(value: string): boolean | Promise<boolean>;
```suggestion
	isValueValid?(value: string): Promise<boolean>;
```
to keep the same type

2023-07-06 08:13 UTC, SheepFromHeaven commented on src/components/registration_new/agencySelection/agencySelection.tsx
> +	console.log(sessionStorageRegistrationData);
```suggestion
```

2023-07-06 08:13 UTC, SheepFromHeaven commented on src/components/registration_new/agencySelection/agencySelection.tsx
> +					setResults([]);
don't we need some kind of error handling? Either displaying the error to the user or trying to reaload a certain amount of time before displaying it.

2023-07-06 08:13 UTC, SheepFromHeaven commented on src/components/registration_new/agencySelection/agencySelectionResults.tsx
> +		sessionStorageRegistrationData.agencyId || undefined
Why do we need this undefined? O.o

2023-07-06 08:13 UTC, SheepFromHeaven commented on src/components/registration_new/agencySelection/agencySelectionResults.tsx
> +			})
```suggestion
			!results?.every((agency) => agency.external)
```

2023-07-06 08:13 UTC, SheepFromHeaven commented on src/components/registration_new/agencySelection/agencySelectionResults.tsx
> +	useEffect(() => {
This whole use effect could be written more reader friendly by:

1. changing the else if's to ifs + return
2. naming the cases (e.g. exactlyOneExternalAgency for the first one)

2023-07-06 08:13 UTC, SheepFromHeaven commented on src/components/registration_new/agencySelection/agencySelectionResults.tsx
> +		// eslint-disable-next-line react-hooks/exhaustive-deps
Why disable lint here? If this rule is not wanted, we should disable it overall

2023-07-06 08:13 UTC, SheepFromHeaven commented on src/components/registration_new/agencySelection/agencySelectionResults.tsx
> +			{results !== undefined && !isLoading && !isConsultantLink && (
```suggestion
			{!!results && !isLoading && !isConsultantLink && (
```

2023-07-06 08:13 UTC, SheepFromHeaven commented on src/components/registration_new/infoDrawer/infoDrawer.tsx
> +			event.type === 'keydown' &&
```suggestion
			event?.type === 'keydown' &&
```

2023-07-12 17:17 UTC, RunzelRosinchen commented on src/components/registration_new/agencySelection/agencySelection.tsx
> +					setResults([]);
Will clarify with UX

2023-07-17 16:00 UTC, SheepFromHeaven approved these changes
Well...good luck merging 🙈

2023-07-17 19:24 UTC, merged