fix: Remove unused user roles
virtualidentityag/diakonie-onlineBeratung-frontend pull request #3
Opened 2021-04-09 12:54 UTC by amannn

There are three places where user roles are still referenced, however they're only in mock data:
1. `api.v1.login.json`
2. `service.users.data.askers.json`
3. `service.users.data.consultants.json`

Since I guess these reflect the actual responses from backend services, I left them in place for now. We won't be able to use them, since we've removed the properties from the interfaces. Let me know however, if you'd like to have them removed from the fixtures as well!

2021-04-12 13:48 UTC, koepferd commented
Looks good. Please also remove the user roles from the fixtures since we won't need them.

2021-04-12 13:49 UTC, koepferd requested changes
Looks good. Please also remove the user roles from the fixtures since we won't need them.

2021-04-13 09:22 UTC, amannn commented
> Looks good. Please also remove the user roles from the fixtures since we won't need them.

Removed them now 👍

2021-04-14 14:13 UTC, koepferd approved these changes

2021-04-14 14:29 UTC, merged