refactor!: Use a single page for all registration pages
virtualidentityag/diakonie-onlineBeratung-frontend pull request #4
Opened 2021-04-12 14:59 UTC by amannn

Previously we created all necessary registration pages with the `HTMLWebpackPlugin`. Now there's only a single page generated that renders the correct registration content based on the URL.

## Proposed Changes

 - Refactor registration to use a single HTML page that can be configured with API data (related nginx change: https://github.com/virtualidentityag/diakonie-onlineBeratung-backend/pull/1).
 - Unify consulting type to number and avoid writing it to the DOM
 - Minor adaptions to the registration data structure: 
    - Introduce `requiredAidMissingRedirectUrl` to replace u25 logic in registration and hardcoded redirect URL.
    - German slugs are used for the resorts to avoid the app from having to know them and mappings.
    - The consulting type of a resort was converted to be a number (at least that is what the majority of the app has used so far).

Related backend change: https://github.com/virtualidentityag/diakonie-onlineBeratung-backend/pull/1

2021-04-12 15:33 UTC, amannn commented on .github/workflows/build.yml
> +                  eslint_extensions: js,ts,tsx
I noticed that the default here is "JS" and therefore TypeScript files apparently weren't linted. I got rid of the only JS file in this PR and therefore this action began to fail, as no files matched anymore.

Note that the action also changed the owner.

2021-04-12 15:33 UTC, amannn commented on config/webpack.config.js
> -			new HtmlWebpackPlugin({
FYI I did a quick diff of this file with a freshly ejected CRA app.

These are the differences:
 - We includeoad the SASS config for every stylesheet
 - The target file name was made dynamic (since we have multiple entry points)
 - The manifest plugin is commented out
 - Fast Refresh was added in a newer CRA version

2021-04-12 15:33 UTC, amannn commented on config/webpack.config.js
> -				title: 'Registrierung Suchtberatung',
I noticed that the `app` chunk is loaded by default, so that's the place where we can add the routing.

2021-04-12 15:33 UTC, amannn commented on src/api/apiGetResortData.ts
> +// TODO: This should be moved to the API at some point
Can be replaced once we have the new endpoint.

2021-04-12 15:33 UTC, amannn commented on src/api/apiGetResortData.ts
> +	'suchtberatung': {
Previously we had english identifiers here (e.g. `addiction`), but some where already German (e.g. `gemeinsamstatteinsam`). Now I've used the German slug consistently to be able to remove mappings. This is the slug that we'd have to pass to the endpoint then.

2021-04-12 15:33 UTC, amannn commented on src/api/apiGetResortData.ts
> +		requiredAidMissingRedirectUrl: 'https://www.u25.de/helpmail/',
The new property as discussed.

2021-04-12 15:33 UTC, amannn commented on src/api/apiGetResortData.ts
> +	'jungen-und-maenner': {
I noticed this is not present in [the nginx config](https://github.com/virtualidentityag/diakonie-onlineBeratung-backend/tree/master/nginx/conf/locations). We discussed this in a call: This was probably never rolled out.

2021-04-12 15:33 UTC, amannn commented on src/api/apiGetResortData.ts
> +		foundData = registrationData[params.resortName];
Previously the `consultingType` from the webpack config restricted which registration data can be read. Now we're only checking if there's a resort with the given name, not considering the consulting type. Is this ok?

2021-04-12 15:33 UTC, amannn commented on src/api/apiGetResortData.ts
> +		foundData = registrationData[params.resortName];
Discussed in a call: Probably the `consultingType` was the property that was used to resolve registration data previously but due to an edge case, resolving based on a resort name was also necessary to avoid ambiguity. At this point we could have removed the resolving by consulting type since it wasn't needed anymore, but it was left in place.

Therefore it should be safe to remove this part.

2021-04-12 15:33 UTC, amannn commented on src/api/fetchData.ts
> -						: redirectToErrorPage(error);
Previously it was possible that when an unhandled error was encountered during the registration and the user was on the u25 page, we'd redirect to helpmail. Now we're not able to do this anymore, since when an error occurs we don't know what kind of resort it is that the user is looking for and we don't have a redirect URL.

The redirect is still in place for the case when the user access the u25 page and has no `aid` since we have sufficient data in this case.

2021-04-12 15:33 UTC, amannn commented on src/components/app/AuthenticatedApp.tsx
> +import * as React from 'react';
I've moved most of the app here. This allows us to use `App` itself just for the routing and mount the actual app code only when the user is authenticated (hence the name).

2021-04-12 15:33 UTC, amannn commented on src/components/app/app.tsx
> +				<Route path="/:resortName/registration">
Note that a trailing slash also works.

2021-04-12 15:33 UTC, amannn commented on src/components/app/authenticatedApp.styles.scss
> -		}
I'm not sure when this could have matched? Previously the registration was completely separate from the regular app, right?

2021-04-12 15:33 UTC, amannn commented on src/components/registration/Registration.tsx
> +import { useParams } from 'react-router-dom';
This component was a bit larger and handled a few things. I've extracted the form into a separate component now with the benefit of being able to mount it only when we have the registration data. Does that make sense to you?

2021-04-12 15:33 UTC, amannn commented on src/components/registration/Registration.tsx
> +				console.log(error);
I've looked at some similar components and saw that API errors are just logged to the console and not displayed to the user. Is this correct? The page might not be useable to the user then though when there's no visual feedback about errors.

2021-04-12 15:33 UTC, amannn commented on src/components/registration/Registration.tsx
> +				console.log(error);
We made a note about this to potentially address it later.

2021-04-12 15:33 UTC, amannn commented on src/components/registration/Registration.tsx
> +			<Stage hasAnimation isReady={registrationData != null} />
I've added a new `isReady` prop to the stage so it can be used as a loader until we have the necessary data. The new prop is opt-in and the other call sites can remain as-is.

2021-04-12 15:33 UTC, amannn commented on src/components/registration/RegistrationForm.tsx
> +};
A copy-paste from the old component. The only difference is that registration data is now received via a prop.

2021-04-12 15:33 UTC, amannn commented on src/components/stage/stage.tsx
> +			})}
As discussed, I began introducing this library for handling conditional class names now.

2021-04-12 15:33 UTC, amannn commented on src/globalState/interfaces/ResortDataInterface.ts
> +	consultingType: number;
Previously this was a string, but I noticed it was used as a `number` in the registration form. Therefore I've consistently used a number now.

Previously this wasn't an issue because the consulting type was defined as a string, written to the DOM, read from there and then converted to a number.

2021-04-12 15:33 UTC, amannn commented on src/pages/app.html
> -		<% } else if(type === 'error') { %>
I guess these are no longer necessary, right?

Edit: I've added a effect in `Registration.tsx` since we read this in `getConsultingTypeFromRegistration`. I guess potentially we could also resolve that and pass the consulting type explicitly via JS and avoid the DOM.

I could look into that in a follow-up if desired.

2021-04-12 15:33 UTC, amannn commented on src/pages/app.html
> -		<% } else if(type === 'error') { %>
This is resolved now. We don't need to write to the DOM anymore and pass the values via JS around as necessary.

2021-04-12 15:33 UTC, amannn commented on src/resources/scripts/helpers/resorts.ts
> -	getConsultingTypeFromRegistration() === 1;
Handled via `requiredAidMissingRedirectUrl` now.

2021-04-12 15:33 UTC, amannn commented on src/resources/scripts/i18n/de/registration.ts
> +	'title.start': 'Registrierung',
Previously we've defined the page title in the webpack config. Now we use a label for this.

2021-04-12 15:39 UTC, amannn commented on src/components/session/SessionItemComponent.tsx
> +	}, [activeSession.session]);
We need to fetch the resort data now and can't read it statically.

2021-04-20 11:46 UTC, koepferd commented on src/api/apiGetResortData.ts
> +	'suchtberatung': {
Nice 👏🏻

2021-04-20 11:49 UTC, koepferd commented on src/api/apiGetResortData.ts
> +	'jungen-und-maenner': {
Yes, this will be rolled out beginning of May 👌🏻
The updated nginx config will be release then.

2021-04-20 11:51 UTC, koepferd commented on src/api/apiGetResortData.ts
> +export const apiGetResortData = async (params: {
Please rename, as we decided to keep the terminology consultingType for now.

2021-04-28 08:46 UTC, koepferd requested changes

2021-04-28 08:46 UTC, koepferd commented on src/components/session/SessionItemComponent.tsx
> +	}, [activeSession.session]);
We resolved this.
Also my tests look good :-)

2021-04-28 08:46 UTC, koepferd commented on src/components/registration/registrationForm.styles.scss
> +	&__generalInformation {
Please check the styles again - I think the automerge went wrong since this classname is unused.

2021-04-28 11:53 UTC, amannn commented on src/components/registration/registrationForm.styles.scss
> +	&__generalInformation {
Good point, thanks! Seems like it was already unused on `develop`.

2021-04-28 13:13 UTC, koepferd approved these changes

2021-04-28 13:27 UTC, merged