OB-6777: Multiple topics selected with repeated name
virtualidentityag/diakonie-onlineBeratung-frontend pull request #74
Opened 2024-02-27 17:34 UTC by pnboliveira

2024-03-05 09:31 UTC, janrembold requested changes
There are some Linting/Prettier issues in your code. Would be good to activate this in your dev environment so it gets linted immediately on save. 

Please also check those messages of unused imports and the unused IMeteorLoginToken interface. Those can be removed.

2024-03-05 09:31 UTC, janrembold commented on src/components/registration/topicSelection/TopicSelection.tsx
>  		return topics?.filter((topic) => topic?.id === mainTopicId)?.[0];
This is only a boyscout task, as it was there before, but could you change this to `topics?.find(...)` as `filter` always searches the whole array and only the first element gets pcked up

2024-03-06 00:24 UTC, web-mi approved these changes

2024-03-06 08:18 UTC, janrembold approved these changes
🚀

2024-03-06 08:33 UTC, merged